[package]
name = "asciidf"
version = "0.1.0"
authors = ["Karthik Karanth <karanth.karthik@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nalgebra-glm = "0.8.0"
colored = "2"
term_size = "0.3.2"
wasm-bindgen = "0.2"
