[package]
name = "asciidf"
version = "0.1.0"
authors = ["Karthik Karanth <karanth.karthik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.8.0"
colored = "2"
term_size = "0.3.2"
